---
.gitlab-ci.yml:
  override: true
  custom:
    custom_stages:
      - syntax
      - unit
      - deploy
    custom_jobs:
      include:
        - project: puppet/tools
          file: gitlab-ci.yml
          ref: master

.devcontainer/devcontainer.json:
  delete: true
.devcontainer/Dockerfile:
  delete: true
.devcontainer/README.md:
  delete: true
appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.vscode/extensions.json:
  delete: true

spec/spec_helper.rb:
  mock_with: ':mocha'
  coverage_report: true
  minimum_code_coverage_percentage: 80
  hiera_config_ruby: "File.expand_path(File.join(__FILE__, '../fixtures/hiera.yaml'))"
spec/default_facts.yml:
  extra_facts:
    jitsi:
      installed: true
      running: true
      version: 0.0.1
.rubocop.yml:
  default_configs:
    Style/RegexpLiteral:
      Description: "Prefer simple style with slashes"
      EnforcedStyle: slashes
